name: "Get latests release of a repository"
inputs:
  repository:
     required: true
     description: "The URL of the repository to be checked."

outputs:
  version:
    description: "The tag of the latest release."
    value: ${{ steps.release.outputs.value }}

runs:
  using: "composite"
  steps:
    - name: Extract github repo
      id: gh-repo
      run: |
        URL=$(echo ${{ inputs.repository }} | sed 's/^.*github\.com\/\([[:alnum:]\-]\+\/[[:alnum:]\-]\+\)\/\?$/\1/;t;Q1')
        echo "value=$URL" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get latest release
      id: release
      run: |
        TAG=$(curl -sL https://api.github.com/repos/${{ steps.gh-repo.outputs.value }}/releases/latest | jq -r '.tag_name')
        echo "value=$TAG" >> $GITHUB_OUTPUT
      shell: bash

